---
substitutions:
  _SERVICE_NAME: '${REPO_NAME}'
  _IMAGE_PATH: 'eu.gcr.io/${PROJECT_ID}/${BRANCH_NAME}/${REPO_NAME}'
  _IMAGE_VERSION: '1.7.2'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_PATH}:${BUILD_ID}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_IMAGE_PATH}:${BUILD_ID}', '${_IMAGE_PATH}:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_IMAGE_PATH}:${BUILD_ID}', '${_IMAGE_PATH}:${_IMAGE_VERSION}']
- name: 'eu.gcr.io/${PROJECT_ID}/${BRANCH_NAME}/helm:latest'
  args: ['scripts/helm-deploy']
  env:
    - 'REGION=${LOCATION}'
    - 'GCLOUD_PROJECT=${PROJECT_ID}'
    - 'REGISTRY_LOCATION=${PROJECT_ID}/${BRANCH_NAME}'
    - 'SERVICE_NAME=${_SERVICE_NAME}'
  secretEnv:
    - CLUSTER_NAME

images:
  - ${_IMAGE_PATH}:latest
  - ${_IMAGE_PATH}:${BUILD_ID}
  - ${_IMAGE_PATH}:${_IMAGE_VERSION}

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/cluster-name/versions/latest
    env: 'CLUSTER_NAME'
