---
substitutions:
  _CLUSTER_NAME: '${CLUSTER_NAME}'
  _SERVICE_NAME: '${REPO_NAME}'
  _IMAGE_PATH: 'eu.gcr.io/${PROJECT_ID}/${BRANCH_NAME}/${REPO_NAME}'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_PATH}:${BUILD_ID}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_IMAGE_PATH}:${BUILD_ID}', '${_IMAGE_PATH}:latest']
- name: 'eu.gcr.io/${PROJECT_ID}/${BRANCH_NAME}/helm:latest'
  args: ['scripts/helm-deploy']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=${LOCATION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${CLUSTER_NAME}'
    - 'GCLOUD_PROJECT=${PROJECT_ID}'
    - 'REGISTRY_LOCATION=${PROJECT_ID}/${BRANCH}'
    - 'SERVICE_NAME=${_SERVICE_NAME}'

images:
  - ${_IMAGE_PATH}:latest
  - ${_IMAGE_PATH}:${BUILD_ID}
